# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dummy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dummy  pod 'Alamofire'
  pod 'DZNEmptyDataSet'
  pod 'Kingfisher', '~> 7.0'
  pod 'MediaBrowser'
  pod 'SwiftMessages'
  pod 'PopupKit'
  pod 'FLAnimatedImage'
  pod 'Gifu'
  pod 'SwiftKeychainWrapper'
  pod 'IQKeyboardManager'
  pod 'NVActivityIndicatorView'
  pod 'AssistantKit'
  pod 'Alamofire'
  pod 'TwilioChatClient', '~> 4.0'

end
